package dto;

public enum RequestCode {
	GET_PLAYINFO_TIME,
	GET_PHONE_VAILD,
	GET_PRINTPHONE_STRING,
	GET_PRINTRESNUM_STRING,
    POST_RESERVE_RESERVEDTO,
    GET_PHONENUMBER_STRING,
    GET_MEMBERINFO_STRING,
    GET_RESERVE_BYID,
    GET_RESERVE_BYPHONE,
    DELETE_RESERVE_BYID,
    GET_COST_RESERVATIONDTO,
    POST_LOGIN_IDANDPASS
}
